Xvibe/multiple domains for organization
Energinet-DataHub/geh-market-participant pull request #1000
Opened 2024-10-21 11:50 UTC by vbelinschi

## Description

## References

* #0000

2024-10-22 14:27 UTC, defectiveAi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/ALL/Model/202410211100 Organization Domain table.sql
> +    ChangedByIdentityId uniqueidentifier NOT NULL
Need support for DeletedByIdentityId, for when a domain is removed.

2024-10-22 14:30 UTC, defectiveAi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/ALL/Model/202410211100 Organization Domain table.sql
> +SELECT NEWID(), Id, Domain, Version, ChangedByIdentityId
Is Version not just 1 always during migration?

2024-10-22 14:32 UTC, defectiveAi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/OrganizationDomain.cs
> +    public static bool IsValid(IEnumerable<string> values)
I would probably keep the old singular API, then use All() whenever multiple domains need validation.

2024-10-22 14:35 UTC, defectiveAi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Model/OrganizationDomainEntity.cs
> +public sealed class OrganizationDomainEntity : IAuditedEntity
There is another interface for supporting deletion.

2024-10-22 14:37 UTC, defectiveAi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/OrganizationAuditLogRepository.cs
>              .Add(OrganizationAuditedChange.Name, entity => entity.Name, AuditedChangeCompareAt.Creation)
How do we get the old audits out, for domain changes on previous table?

2024-10-22 14:37 UTC, defectiveAi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/OrganizationAuditLogRepository.cs
> +            .Add(OrganizationAuditedChange.Domain, entity => string.Join(";", entity.Domain), AuditedChangeCompareAt.Creation)
There are examples for adding deletion support.

2024-10-22 14:40 UTC, defectiveAi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Repositories/OrganizationRepositoryTests.cs
> +    public async Task AddOrUpdateAsync_OneOrganizationWitsDuplicateDomains_ReturnsError()
nitpick: Wits > With

2024-10-22 14:41 UTC, defectiveAi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Organization.cs
> +    public IEnumerable<OrganizationDomain> Domains { get; set; }
Consider if it makes sense to make this HashSet or interface of one.

2024-10-22 14:44 UTC, defectiveAi requested changes
Mostly unsure if add/delete of domains is correctly audited + if/how audit of old values is kept. Some tests will show that.

2024-10-28 07:40 UTC, vbelinschi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/ALL/Model/202410211100 Organization Domain table.sql
> +    ChangedByIdentityId uniqueidentifier NOT NULL
done

2024-10-28 07:40 UTC, vbelinschi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/ALL/Model/202410211100 Organization Domain table.sql
> +SELECT NEWID(), Id, Domain, Version, ChangedByIdentityId
ok, I thought we should keep the versions

2024-10-28 07:40 UTC, vbelinschi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/OrganizationDomain.cs
> +    public static bool IsValid(IEnumerable<string> values)
done

2024-10-28 07:41 UTC, vbelinschi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Model/OrganizationDomainEntity.cs
> +public sealed class OrganizationDomainEntity : IAuditedEntity
done

2024-10-28 07:41 UTC, vbelinschi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/OrganizationAuditLogRepository.cs
>              .Add(OrganizationAuditedChange.Name, entity => entity.Name, AuditedChangeCompareAt.Creation)
I added sql script to move the old logs to the new table as well

2024-10-28 07:41 UTC, vbelinschi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/OrganizationAuditLogRepository.cs
> +            .Add(OrganizationAuditedChange.Domain, entity => string.Join(";", entity.Domain), AuditedChangeCompareAt.Creation)
done

2024-10-28 07:41 UTC, vbelinschi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/GetOrganizationAuditLogsHandlerIntegrationTests.cs
>              },
added

2024-10-28 07:42 UTC, vbelinschi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Repositories/OrganizationRepositoryTests.cs
> +    public async Task AddOrUpdateAsync_OneOrganizationWitsDuplicateDomains_ReturnsError()
🙈

2024-10-28 07:43 UTC, vbelinschi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Organization.cs
> +    public IEnumerable<OrganizationDomain> Domains { get; set; }
I changed the OrganizationDomain to record, don't know if we get anything from changing to HashSet as well

2024-10-29 08:42 UTC, defectiveAi approved these changes

2024-10-29 08:43 UTC, defectiveAi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Organization.cs
> +    public IEnumerable<OrganizationDomain> Domains { get; set; }
HashSet may give a simpler difference comparison when updaring the entity, assuming EF handles it correctly.

2024-10-29 13:05 UTC, vbelinschi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Organization.cs
> +    public IEnumerable<OrganizationDomain> Domains { get; set; }
I started to change it to HashSet, but I think it's too much work for little gain.
Fx.: in `UpdateOrganizationHandler` we can't just set `organization.Domain = newDomains`, we have to clear the HashSet and add the new ones to it.

2024-10-29 13:05 UTC, merged