597: Validate chosen combination of eic functions in backend
Energinet-DataHub/geh-market-participant pull request #136
Opened 2022-05-18 11:40 UTC by mbusk88

## References

* #597

2022-05-18 12:09 UTC, xnetsrak requested changes
looks fine, but seems you missed a assert . otherwise ok.

2022-05-18 12:20 UTC, xnetsrak submitted a review, later dismissed

2022-05-18 13:45 UTC, defectiveAi commented on source/Energinet.DataHub.MarketParticipant.Domain/Energinet.DataHub.MarketParticipant.Domain.csproj
> +    <PackageReference Include="FluentValidation" Version="10.4.0" />
You can remove this again.

2022-05-18 14:13 UTC, michaelmajgaard commented on source/Energinet.DataHub.MarketParticipant.Domain/Services/Rules/CombinationOfBusinessRolesRuleService.cs
> +            GridAccessProviderRole = new GridAccessProviderRole();
`GridAccessProviderRole` is not used, is this an oversight? And also, all of the properties except `AllSets` can be local variable in constructor.

2022-05-20 10:41 UTC, xnetsrak approved these changes

2022-05-20 10:43 UTC, merged