Added ..Integration.sln + ..Integration.Model package project
Energinet-DataHub/geh-market-participant pull request #14
Opened 2022-02-11 13:16 UTC by michaelmajgaard

2022-02-15 15:33 UTC, defectiveAi submitted a review, later dismissed
Minor stuff

2022-02-15 15:33 UTC, defectiveAi commented on source/Energinet.DataHub.MarketParticipant.Integration.Model.Tests/Parsers/OrganizationChangedEventParserTests.cs
> +            Assert.Equal(@event, actaulEvent);
actaulEvent

2022-02-15 15:33 UTC, defectiveAi commented on .github/actions/publish-nuget-package/action.yml
> +# https://github.com/actions/runner/pull/612
What to do with these links?

2022-02-15 15:41 UTC, FirestarJes requested changes

2022-02-15 15:41 UTC, FirestarJes commented on .github/workflows/publish-messagehub-model.yml
> +# Copyright 2020 Energinet DataHub A/S
Should the file perhaps be renamed to publish-marketparticipant-model.yml?

2022-02-15 15:41 UTC, FirestarJes commented on source/Energinet.DataHub.MarketParticipant.Integration.Model/source/Energinet.DataHub.MarketParticipant.Integration.Model/Guard.cs
> +﻿// Copyright 2020 Energinet DataHub A/S
Is there a reason you aren't using the guard in the utilities project? PErhaps merge from main if you don't have it yet?

2022-02-15 15:41 UTC, FirestarJes commented on source/Energinet.DataHub.MarketParticipant.Integration.Model/source/Energinet.DataHub.MarketParticipant.Integration.Model/Energinet.DataHub.MarketParticipant.Integration.Model.csproj
> +      <Access>Public</Access>
Should probably be Internal, since we don't want our protobof classes visible outside of our project.

2022-02-15 15:48 UTC, FirestarJes commented on source/Energinet.DataHub.MarketParticipant.Integration.Model/source/Energinet.DataHub.MarketParticipant.Integration.Model/Guard.cs
> +﻿// Copyright 2020 Energinet DataHub A/S
nevermind, it's to seperate the to, as this is it's own project/package.

2022-02-16 07:44 UTC, michaelmajgaard commented on source/Energinet.DataHub.MarketParticipant.Integration.Model.Tests/Parsers/OrganizationChangedEventParserTests.cs
> +            Assert.Equal(@event, actaulEvent);
fixed

2022-02-16 07:44 UTC, michaelmajgaard commented on .github/actions/publish-nuget-package/action.yml
> +# https://github.com/actions/runner/pull/612
fixed

2022-02-16 07:44 UTC, michaelmajgaard commented on .github/workflows/publish-messagehub-model.yml
> +# Copyright 2020 Energinet DataHub A/S
fixed

2022-02-16 07:46 UTC, michaelmajgaard commented on source/Energinet.DataHub.MarketParticipant.Integration.Model/source/Energinet.DataHub.MarketParticipant.Integration.Model/Energinet.DataHub.MarketParticipant.Integration.Model.csproj
> +      <Access>Public</Access>
fixed

2022-02-16 07:50 UTC, FirestarJes approved these changes

2022-02-16 08:05 UTC, merged