User roles assignment audit log
Energinet-DataHub/geh-market-participant pull request #351
Opened 2022-12-15 12:15 UTC by xnetsrak

## Description

## References

* #0000

2022-12-15 12:49 UTC, FirestarJes requested changes

2022-12-15 12:49 UTC, FirestarJes commented on source/Energinet.DataHub.MarketParticipant.ApplyDBMigrationsApp/Scripts/LocalDB/202212131417 Add UserRoleAssignmentAuditLog Table.sql
> +GO
This script should be added to all environments

2022-12-15 12:49 UTC, FirestarJes commented on source/Energinet.DataHub.MarketParticipant.Domain/Model/Users/UserRoleAssignmentChangeAuditLog.cs
> +public enum UserRoleAssignmentTypeAuditLog
Filename should match Enumname

2022-12-15 12:49 UTC, FirestarJes commented on source/Energinet.DataHub.MarketParticipant.Domain/Repositories/IUserRoleAssignmentAuditLogEntryRepository.cs
> +    /// Repository giving access to grid area audit log entries
Comment should be updated to reflect that this is Role Assigments and not grid areas

2022-12-15 12:49 UTC, FirestarJes commented on source/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/UserRoleAssignmentAuditLogEntryRepository.cs
> +        public Task InsertAuditLogEntryAsync(UserRoleAssignmentAuditLogEntry logEntry)
What does this implementation do differently than the one it calls, it appears t only be a different name?

2022-12-15 12:49 UTC, FirestarJes commented on source/Energinet.DataHub.MarketParticipant.EntryPoint.WebApi/Controllers/UserRoleAssignmentAuditLogController.cs
> +    [HttpGet("auditlogs/userroles/user/{userId:guid}/actor/{actorId:guid}")]
Seems excessive, could this be shortened a bit.

2022-12-15 13:30 UTC, FirestarJes approved these changes

2022-12-19 15:01 UTC, defectiveAi approved these changes

2022-12-19 15:01 UTC, merged