feat: deactivate user
Energinet-DataHub/geh-market-participant pull request #551
Opened 2023-06-12 13:47 UTC by michaelmajgaard

2023-06-12 14:18 UTC, defectiveAi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Users/User.cs
> +    public async Task DeactivateAsync(IUserIdentityRepository userIdentityRepository)
I would not do this. Currently, only IDP user identity has a concept of enabled/disabled, and both entites function as two separate aggregate roots.

2023-06-12 14:20 UTC, defectiveAi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/DeactivateUserTests.cs
> +        userEntity.RoleAssignments.Add(new UserRoleAssignmentEntity
Use `AssignUserRoleAsync`

2023-06-12 14:21 UTC, defectiveAi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/DeactivateUserTests.cs
> +        Assert.NotEmpty(user.RoleAssignments);
This really needed? You are testing the test?

2023-06-12 14:22 UTC, defectiveAi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/DeactivateUserTests.cs
> +        Assert.Empty(actual.RoleAssignments);
Add Assert.NotNull instead of !

2023-06-12 14:23 UTC, defectiveAi requested changes
Change `user.DeactivateAsync`

2023-06-12 14:40 UTC, michaelmajgaard commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Application/Handlers/User/InviteUserHandler.cs
> +            NotFoundValidationException.ThrowIfNull(userRole, $"The specified user role {userRole} was not found.");
fixed

2023-06-12 14:40 UTC, michaelmajgaard commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Users/User.cs
> +    public async Task DeactivateAsync(IUserIdentityRepository userIdentityRepository)
fixed

2023-06-12 14:40 UTC, michaelmajgaard commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/DeactivateUserTests.cs
> +        Assert.NotEmpty(user.RoleAssignments);
fixed

2023-06-12 14:40 UTC, michaelmajgaard commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.IntegrationTests/Hosts/WebApi/DeactivateUserTests.cs
> +        Assert.Empty(actual.RoleAssignments);
fixed

2023-06-13 06:04 UTC, defectiveAi approved these changes

2023-06-13 06:07 UTC, merged