Feat: Add Actor Credentials
Energinet-DataHub/geh-market-participant pull request #671
Opened 2023-10-27 21:48 UTC by FirestarJes

2023-10-30 12:08 UTC, defectiveAi requested changes

2023-10-30 12:08 UTC, defectiveAi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Repositories/ActorErrorHandler.cs
> +        ActorError.ClientSecretCredentialsConflict => new ValidationException("An actor with the same Client secret identifier already exists"),
ClientSecretCredentialsConflict is not a domain/validation error, as the secret is always created by infrastructure. If this conflict happens, we have a bug.

In the other case, it is a validation error, as a user can upload the same cert twice for two different actors.

2023-10-30 12:08 UTC, defectiveAi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/ActorRepository.cs
> +        catch (DbUpdateException ex) when (
Do not catch this one, see previous comment.

2023-10-30 12:25 UTC, FirestarJes commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Infrastructure/Persistence/Repositories/ActorRepository.cs
> +        catch (DbUpdateException ex) when (
Fixed

2023-10-30 12:26 UTC, FirestarJes commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Repositories/ActorErrorHandler.cs
> +        ActorError.ClientSecretCredentialsConflict => new ValidationException("An actor with the same Client secret identifier already exists"),
Fixed

2023-10-30 12:26 UTC, FirestarJes commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Actor.cs
> +    public ICollection<ActorCredentials> Credentials { get; }
Fixed

2023-10-30 13:47 UTC, defectiveAi commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Actor.cs
> +        ActorCredentials credentials)
Remove credentials from ctor. We do not have credentials at construction time.

2023-10-30 16:18 UTC, FirestarJes commented on source/marketparticipant/Energinet.DataHub.MarketParticipant.Domain/Model/Actor.cs
> +        ActorCredentials credentials)
Fixed

2023-10-31 06:11 UTC, defectiveAi approved these changes

2023-10-31 06:11 UTC, merged