Mbes/508 integration of actor register with azure ad
Energinet-DataHub/geh-market-participant pull request #93
Opened 2022-04-07 08:11 UTC by mbusk88

## Description

Not done yet, working on a couple of files, but almost there...

## References

* #508

2022-04-27 07:48 UTC, defectiveAi reviewed
Looks very good!

2022-04-27 07:48 UTC, defectiveAi commented on source/Energinet.DataHub.MarketParticipant.Domain/Services/IActiveDirectoryService.cs
> +        Task<AppRegistrationSecret> CreateSecretForAppRegistrationAsync(string appRegistrationObjectId);
Because the type is string, I do not know which value to give in here. Is it ExternalActorId, is it something else? Is it even a Guid? Consider adding types for the different ids for all three calls.

2022-04-27 07:48 UTC, defectiveAi commented on source/Energinet.DataHub.MarketParticipant.Domain/Services/IActiveDirectoryService.cs
> +        /// <returns>A <see cref="Task{boolean}"/> representing whether the deletion of the app was successful or not. The value 'true' indicates the app was deleted successfully.</returns>
Comment claims a bool will be returned, but the method does not do that. Is the comment wrong, or the method?

2022-04-27 07:48 UTC, defectiveAi commented on source/Energinet.DataHub.MarketParticipant.Domain/Services/IActiveDirectoryService.cs
> +        /// <returns>A <see cref="Task{boolean}"/> representing whether the deletion of the app was successful or not. The value 'true' indicates the app was deleted successfully.</returns>
Comment claims a bool will be returned, but the method does not do that. Is the comment wrong, or the method?

2022-04-27 07:48 UTC, defectiveAi commented on source/Energinet.DataHub.MarketParticipant.Infrastructure/Services/ActiveDirectoryB2CRolesProvider.cs
> +            _appObjectId = string.IsNullOrWhiteSpace(appObjectId)
Remove appObjectId null check. You are asking dependency injection to provide you with graphClient and appObjectId - expect DI to have the responsibility to create object correctly.

2022-04-27 07:48 UTC, defectiveAi commented on source/Energinet.DataHub.MarketParticipant.Domain/Model/ActiveDirectory/ActiveDirectoryRoles.cs
> +    public sealed record ActiveDirectoryRoles
I feel this object is unnecessary. Returning IList<ActiveDirectoryRole> (or even better IEnumerable<ActiveDirectoryRole>, since I assume the list is read-only) tells the same information using less code.

2022-04-27 07:48 UTC, defectiveAi commented on source/Energinet.DataHub.MarketParticipant.Infrastructure/Services/ActiveDirectoryB2CRolesProvider.cs
> +                        _activeDirectoryB2CRoles.DdkId = appRole.Id ?? Guid.Empty;
What does it mean when Guid.Empty is assigned? Will it lead to a crash when assigning the role, or just no access?

2022-04-27 07:48 UTC, defectiveAi commented on source/Energinet.DataHub.MarketParticipant.Infrastructure/Services/ActiveDirectoryB2CRolesProvider.cs
> +                    case "STS":
Do we have control over the names of the roles? Could we use the shorter 'DDQ', 'DDK' instead of the longer names. Or maybe not use DisplayName? Can we add a tag to an app role that we could use instead?

2022-04-27 07:48 UTC, defectiveAi commented on source/Energinet.DataHub.MarketParticipant.Infrastructure/Services/ActiveDirectoryB2cService.cs
> +                // What should be done with this role? To database? Integration event?
We need to be able to edit permissions later. So if servicePrincipal.Id is required for that, we must save it too.

2022-04-27 07:48 UTC, defectiveAi commented on source/Energinet.DataHub.MarketParticipant.Infrastructure/Services/ActiveDirectoryB2cService.cs
> +                    roleIds.Roles.Add(new ActiveDirectoryRole(role.AppRoleId.ToString()!));
Why is there a bang at the end? What can be null here?

2022-04-27 07:48 UTC, defectiveAi commented on source/Energinet.DataHub.MarketParticipant.Infrastructure/Services/ActiveDirectoryB2cService.cs
> +                    roleIds.Roles.Add(new ActiveDirectoryRole(role.AppRoleId.ToString()!));
Why map to ActiveDirectoryRole? The roles are never leaving Infrastructure?

2022-04-27 07:48 UTC, defectiveAi commented on source/Energinet.DataHub.MarketParticipant.Infrastructure/Services/ActiveDirectoryB2cService.cs
> +                    roleIds.Roles.Add(new ActiveDirectoryRole(role.AppRoleId.ToString()!));
Why map to ActiveDirectoryRole? The roles are never leaving Infrastructure?

2022-04-27 07:48 UTC, defectiveAi commented on source/Energinet.DataHub.MarketParticipant.Infrastructure/Services/ActiveDirectoryB2cService.cs
> +                            ResourceAccess = resourceAccesses.Select(resourceAccess => new ResourceAccess { Id = resourceAccess.Id, Type = "Role" }).ToList(),
No need to new again? Just assign directly: ResourceAccess = resourceAccesses

2022-04-27 07:48 UTC, defectiveAi commented on source/Energinet.DataHub.MarketParticipant.Infrastructure/Services/ActiveDirectoryB2cService.cs
> +                            ResourceAccess = resourceAccesses.Select(resourceAccess => new ResourceAccess { Id = resourceAccess.Id, Type = "Role" }).ToList(),
No need to new again? Just assign directly: ResourceAccess = resourceAccesses

2022-05-10 07:07 UTC, FirestarJes requested changes

2022-05-10 07:07 UTC, FirestarJes commented on source/Energinet.DataHub.MarketParticipant.Infrastructure/Services/ActiveDirectoryB2cService.cs
> +            }
Should use the same null check as elsewhere, replace with ArgumentNullException.ThrowIfNull, which required a merge with main to get the update to .Net 6

2022-05-10 07:07 UTC, FirestarJes commented on source/Energinet.DataHub.MarketParticipant.Infrastructure/Services/ActiveDirectoryB2cService.cs
> +            Guard.ThrowIfNull(appName, nameof(appName));
Replace with  ArgumentNullException.ThrowIfNull

2022-05-10 07:07 UTC, FirestarJes commented on source/Energinet.DataHub.MarketParticipant.Infrastructure/Services/ActiveDirectoryB2cService.cs
> +            Guard.ThrowIfNull(appId, nameof(appId));
Replace with ArgumentNullException.ThrowIfNull

2022-05-10 07:07 UTC, FirestarJes commented on source/Energinet.DataHub.MarketParticipant.Infrastructure/Services/ActiveDirectoryB2cService.cs
> +            Guard.ThrowIfNull(appRegistrationObjectId, nameof(appRegistrationObjectId));
Replace with ArgumentNullException.ThrowIfNull

2022-05-10 07:07 UTC, FirestarJes commented on source/Energinet.DataHub.MarketParticipant.Infrastructure/Services/ActiveDirectoryB2cService.cs
> +        private async Task<AppRegistrationRole> GrantAddedRoleToServicePrincipalAsync(
Return value is never used, should probably be changed to ValueTask

2022-05-11 07:14 UTC, FirestarJes approved these changes

2022-05-17 09:49 UTC, FirestarJes approved these changes

2022-05-18 06:48 UTC, merged